version: "3.4"

services:
  web_ui:
    build: 
      context: ./web_ui
      target: dev
    command: sh -c "npm i && npm start"
    environment: 
      - BACKEND_HOST=http://localhost:8888
    container_name: gnxi_web_ui_dev
    network_mode: host
    volumes: 
      - ./web_ui:/workspace
  backend:
    build: 
      context: ..
      dockerfile: gnxi_tester/Dockerfile
      target: dev
    command: modd 
    working_dir: /workspace/gnxi_tester
    network_mode: host
    container_name: gnxi_backend_dev
    volumes: 
      - ..:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
